require('mappings/aerial')
require('mappings/general')
require('mappings/gitsigns')
-- require('mappings/lsp')
require('mappings/nvim_tree')
require('mappings/telescope')
require('mappings/trouble')
require('mappings/vimtex')
require('mappings/vimux')
