return function (client, bufnr)
  local bufopts = { noremap=true, silent=true, buffer=bufnr }
  vim.keymap.set('n', 'gd', vim.lsp.buf.definition, bufopts)
  vim.keymap.set('n', 'gD', vim.lsp.buf.declaration, bufopts)
  vim.keymap.set('n', 'gi', vim.lsp.buf.implementation, bufopts)
  vim.keymap.set('n', 'gr', vim.lsp.buf.references, bufopts)
  vim.keymap.set('n', 'K', vim.lsp.buf.hover, bufopts)
  vim.keymap.set('n', '<space>la', vim.lsp.buf.code_action, { noremap=true, silent=true, buffer=bufnr, desc="code actions"})
  vim.keymap.set('n', '<space>lA', vim.lsp.buf.add_workspace_folder, { noremap=true, silent=true, buffer=bufnr, desc="add workspace folder"})
  vim.keymap.set('n', '<space>lD', vim.lsp.buf.remove_workspace_folder, { noremap=true, silent=true, buffer=bufnr, desc="delete workspace folder"})
  vim.keymap.set('n', '<space>lf', vim.lsp.buf.formatting, { noremap=true, silent=true, buffer=bufnr, desc="format file"})
  vim.keymap.set('n', '<space>ll', function() print(vim.inspect(vim.lsp.buf.list_workspace_folders()))  end, { noremap=true, silent=true, buffer=bufnr, desc="list workspace folders"})
  vim.keymap.set('n', '<space>lr', vim.lsp.buf.rename, { noremap=true, silent=true, buffer=bufnr, desc="rename"})
  vim.keymap.set('n', '<space>ls', vim.lsp.buf.signature_help, { noremap=true, silent=true, buffer=bufnr, desc="signature help"})
  vim.keymap.set('n', '<space>lt', vim.lsp.buf.type_definition, { noremap=true, silent=true, buffer=bufnr, desc="type definition"})
  require('aerial').on_attach(client, bufnr)
end
